#!/usr/local/Cellar/php54/5.4.7/bin/php
<?php

include('hooks.php');
include('spyc.php');

echo "------------------>> Starting post-receive loveliness ------------------\n";
// As we created a --bare repo, we need to get the yaml
$yaml = `git show HEAD:boxfile`;
$branch = 'exec('
while read oldrev newrev ref
do
  branch=`echo $ref | cut -d/ -f3`
  echo $branch
done
');'

echo "------------------>> Read boxfile.uat ----------------------------------\n";

// Then, pass it to the yamliser to get an array
$yaml = Spyc::YAMLLoad($yaml);

// Init and run!
$hooks = new gitHooks('post-receive', $branch, $yaml);
$hooks->run();

echo "------------------>> post-receive complete -----------------------------\n";