#!/usr/local/Cellar/php54/5.4.7/bin/php
<?php

include('hooks.php');
include('spyc.php');
echo "------------------>> Starting pre-receive loveliness ------------------\n";
// We can't do anything with the repo here as it hasn't receieve any files from
// the remote yet!
// Then, pass it to the yamliser to get an array
$yaml_file = '/home/mikepear/engni.yaml';

if (file_exists($yaml_file)) {

	$yaml = Spyc::YAMLLoad($yaml_file);
	// Init and run!
	$hooks = new gitHooks('pre-receive', $yaml);
	$hooks->run();

	echo "------------------>> pre-receive complete -----------------------------\n";	
} else {
	echo "------------------>> No YAML found, exiting -----------------------------\n";	
	exit(0);
}